#!/bin/sh
#
# @name Believer Tiltrotor
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Andreas Antener <andreas@uaventure.com>
#
# @output MAIN1 Motor front right
# @output MAIN2 Motor rear left
# @output MAIN3 Motor front left
# @output MAIN4 Motor rear right
# @output MAIN5 Tilt servo right
# @output MAIN6 Tilt servo left
# @output MAIN7 Elevon right
# @output MAIN8 Elevon left
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then


	param set FW_ARSP_MODE 2

	param set FW_L1_PERIOD 18
	param set FW_MAN_R_MAX 35
	param set FW_ACRO_X_MAX   270
	param set FW_ACRO_Y_MAX   270
	param set FW_ACRO_Z_MAX   180
	param set FW_PR_FF    0.35
	param set FW_PR_P 0.08
	param set FW_PSP_OFF  3
	param set FW_P_LIM_MAX    25
	param set FW_P_LIM_MIN    -20
	param set FW_P_RMAX_NEG   60
	param set FW_P_RMAX_POS   60
	param set FW_RR_FF    0.33
	param set FW_RR_P 0.11
	param set FW_YR_FF    0.3
	param set FW_YR_P 0.05

	param set MC_PITCHRATE_D  0.003
	param set MC_PITCHRATE_P  0.11
	param set MC_PITCH_P  5.5
	param set MC_ROLLRATE_D   0.003
	param set MC_ROLLRATE_P   0.11
	param set MC_ROLL_P   5.5
	param set MC_YAWRATE_MAX  120
	param set MC_YAWRATE_P    0.27
	param set MC_YAW_P    2.5

	param set MC_YAWRATE_P 0.3
	param set MPC_LAND_SPEED 1.2
	param set MPC_TKO_SPEED 2.5
	param set MPC_Z_VEL_MAX_UP 3

	param set PWM_RATE 400

	param set SENS_BOARD_ROT 0

	param set VT_B_TRANS_DUR  1
	param set VT_F_TRANS_DUR  3.0
	param set VT_F_TR_OL_TM   5
	param set VT_FW_DIFTHR_EN 1
	param set VT_FW_DIFTHR_SC 0.2
	param set VT_FW_MOT_OFFID 12
	param set VT_FW_PERM_STAB 0
	param set VT_IDLE_PWM_MC 1150
	param set VT_MOT_ID 1234
	param set VT_TILT_FW  1
	param set VT_TILT_MC  0
	param set VT_TILT_TRANS   0.24
	param set VT_TRANS_MIN_TM 4.0
	param set VT_TRANS_P2_DUR 1.5
	param set VT_ELEV_MC_LOCK 0
	param set VT_TYPE 1

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set FW_AIRSPD_MAX 20
	param set FW_AIRSPD_MIN 12
	param set FW_AIRSPD_TRIM 16
fi

set MAV_TYPE 21

set MIXER vtol_convergence

set PWM_OUT 1234

set MIXER_AUX vtol_AAVVT

